name = "ws"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-04"

[miniflare]
durable_objects_persist = true

[build]
command = "npm install && npm test && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"
rules = [
    {type = "ESModule", globs = ["**/*.mjs"]},
    {type = "Data", globs = ["**/*.html"]}
]

[durable_objects]
bindings = [{name = "BROADCAST", class_name = "BroadcastTs"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["BroadcastTs"]
